#!/bin/bash
# 

# Configuration
PROJECT_ID=adsp-capstone-robotics
INSTANCE_NAME="treasure-hunt2"
DB_NAME="sakila"
ROOT_PASSWORD="RootRoot1!"
REGION="us-central1" # Iowa

gcloud config set project $PROJECT_ID

# NOTE: Authentication Check
# Before running any gcloud commands, we ensure there is an active account.
# If no account is found, it triggers the interactive login flow.
if ! gcloud auth list --filter=status:ACTIVE --format="value(account)" | grep -q "@"; then
    gcloud auth login
fi

echo "Enabling required Google Cloud APIs..."

# NOTE: API Enablement
# We enable the following APIs to ensure the script has the necessary permissions:
# 1. sqladmin.googleapis.com: Required to create and manage Cloud SQL instances.
# 2. compute.googleapis.com: Required for networking and infrastructure management.
# 3. servicemanagement.googleapis.com: Required for service control.
# 4. serviceusage.googleapis.com: Required to enable other APIs programmatically.
gcloud services enable \
    sqladmin.googleapis.com \
    compute.googleapis.com \
    servicemanagement.googleapis.com \
    serviceusage.googleapis.com

echo "Starting setup for $INSTANCE_NAME in $REGION..."

# 2. Create Cloud SQL MySQL 5.7 Instance
# Tier db-f1-micro is the smallest instance type available.
# Authorized networks 0.0.0.0/0 opens connection to all internet IPs.
gcloud sql instances create $INSTANCE_NAME \
    --database-version=MYSQL_5_7 \
    --tier=db-f1-micro \
    --region=$REGION \
    --root-password=$ROOT_PASSWORD \
    --authorized-networks=0.0.0.0/0

# 3. Create the database
gcloud sql databases create $DB_NAME --instance=$INSTANCE_NAME

# 4. Download and Prepare Sakila Database
curl -L -O https://downloads.mysql.com/docs/sakila-db.zip
unzip sakila-db.zip
cd sakila-db

# 5. Get Instance IP Address
INSTANCE_IP=$(gcloud sql instances describe $INSTANCE_NAME --format='get(ipAddresses[0].ipAddress)')

# 6. Load Schema and Data into the instance
echo "Loading Sakila schema and data into $INSTANCE_NAME at $INSTANCE_IP..."
# Sakila schema script creates the database structure; data script populates it.
mysql --host=$INSTANCE_IP --user=root --password=$ROOT_PASSWORD < sakila-schema.sql
mysql --host=$INSTANCE_IP --user=root --password=$ROOT_PASSWORD $DB_NAME < sakila-data.sql

# 7. Execute 10 analytics queries
echo "--------------------------------------------------------"
echo "Executing 10 Analytics Queries on Sakila Data:"
echo "--------------------------------------------------------"

function run_query() {
    echo "Query $1: $2"
    mysql --host=$INSTANCE_IP --user=root --password=$ROOT_PASSWORD $DB_NAME -t -e "$3"
    echo "--------------------------------------------------------"
}

run_query "1" "Top 10 actors by number of films they appeared in" \
"SELECT a.first_name, a.last_name, COUNT(fa.film_id) AS film_count FROM actor a JOIN film_actor fa ON a.actor_id = fa.actor_id GROUP BY a.actor_id ORDER BY film_count DESC LIMIT 10;"

run_query "2" "Top 5 most rented movie categories" \
"SELECT c.name, COUNT(r.rental_id) AS rental_count FROM rental r JOIN inventory i ON r.inventory_id = i.inventory_id JOIN film_category fc ON i.film_id = fc.film_id JOIN category c ON fc.category_id = c.category_id GROUP BY c.name ORDER BY rental_count DESC LIMIT 5;"

run_query "3" "Total cumulative revenue per store" \
"SELECT s.store_id, SUM(p.amount) AS total_revenue FROM payment p JOIN rental r ON p.rental_id = r.rental_id JOIN inventory i ON r.inventory_id = i.inventory_id JOIN store s ON i.store_id = s.store_id GROUP BY s.store_id;"

run_query "4" "Customers who have never rented a movie (Target for marketing)" \
"SELECT c.first_name, c.last_name FROM customer c LEFT JOIN rental r ON c.customer_id = r.customer_id WHERE r.rental_id IS NULL;"

run_query "5" "Average film duration (minutes) grouped by category" \
"SELECT c.name, AVG(f.length) AS avg_length FROM film f JOIN film_category fc ON f.film_id = fc.film_id JOIN category c ON fc.category_id = c.category_id GROUP BY c.name ORDER BY avg_length DESC;"

run_query "6" "Total revenue generated by month" \
"SELECT DATE_FORMAT(payment_date, '%Y-%m') AS month, SUM(amount) AS revenue FROM payment GROUP BY month ORDER BY month;"

run_query "7" "Top 5 customers by lifetime payment amount" \
"SELECT c.first_name, c.last_name, SUM(p.amount) AS total_spent FROM customer c JOIN payment p ON c.customer_id = p.customer_id GROUP BY c.customer_id ORDER BY total_spent DESC LIMIT 5;"

run_query "8" "Films that exist in inventory but have NEVER been rented" \
"SELECT f.title FROM film f WHERE f.film_id NOT IN (SELECT DISTINCT i.film_id FROM inventory i JOIN rental r ON i.inventory_id = r.inventory_id);"

run_query "9" "10 Actors who have never performed in a 'Horror' movie" \
"SELECT first_name, last_name FROM actor WHERE actor_id NOT IN (SELECT fa.actor_id FROM film_actor fa JOIN film_category fc ON fa.film_id = fc.film_id JOIN category c ON fc.category_id = c.category_id WHERE c.name = 'Horror') LIMIT 10;"

run_query "10" "Inventory stock levels for the top 10 most popular films at Store 1" \
"SELECT f.title, COUNT(i.inventory_id) as stock FROM film f JOIN inventory i ON f.film_id = i.film_id WHERE i.store_id = 1 GROUP BY f.film_id ORDER BY stock DESC LIMIT 10;"

echo "Setup and verification for '$INSTANCE_NAME' is complete."

echo "--------------------------------------------------------"
echo "CLEANUP OPTIONS"
echo "--------------------------------------------------------"

read -p "Would you like to STOP the instance now to save costs? (y/n): " confirm_stop
if [[ $confirm_stop == [yY] || $confirm_stop == [yY][eE][sS] ]]; then
    echo "Stopping instance $INSTANCE_NAME..."
    gcloud sql instances patch $INSTANCE_NAME --activation-policy=NEVER
else
    echo "Instance remains RUNNING. Remember to stop it later to avoid charges."
fi

read -p "Would you like to DELETE the instance entirely? (y/n): " confirm_delete
if [[ $confirm_delete == [yY] || $confirm_delete == [yY][eE][sS] ]]; then
    echo "Deleting instance $INSTANCE_NAME..."
    gcloud sql instances delete $INSTANCE_NAME --quiet
else
    echo "To DELETE the instance and all data later, run:"
    echo "gcloud sql instances delete $INSTANCE_NAME --quiet"
fi